version: "3.3"

services:
  myApp:
    image: soul0silver/reactjs:latest
    container_name: my-app
    build: .
    ports:
      - 3001:80
    volumes:
      - ./env.js:/usr/share/nginx/html/public/env.js:ro
